name: pq
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip 
  - joblib 
  - keras 
  - pillow 
  - scipy 
  - pandas
  - pip:
    - tensorflow 
    - tk
    - customtkinter
    - scikit-learn 
    - matplotlib 
    - numpy 
    - CTkMessagebox
    - stockwell



